### ISSUE TITLE
[ENHANCEMENT] Container compatibility

### ISSUE THREAD

**Issue by mikejgray** [JarbasAI/skill_easter_eggs#36]
consideration, if running in containers the path to the mp3 file wont be available inside ovos-audio

you can check for 
` os.environ.get("IS_OVOS_CONTAINER") ` and in this case perhaps send the url for the file from github? that would cause OCP to stream it instead of hiting a bad file path

_Originally posted by @JarbasAl in https://github.com/OpenVoiceOS/ovos-skill-easter-eggs/pull/35#discussion_r1452917126_

**Comment by JarbasAl** [comment]
infodumping somer further context, regular sounds dont need this as they are very small, so they are directly sent via the messagebus embedded in the play sound message

the portal song is much larger, its not a short audio, so for OCP this approach doesnt work
