### ISSUE TITLE
sing feedback

### ISSUE THREAD

**Issue by JarbasAl** [JarbasAI/skill_easter_eggs#42]
"can you sing" failed to match

"sing me a song" matched, but it said it did not have its original voice

ovos-tts-server by default uses ap voice, the skill is not handling the case of ovos-tts-server without voice set

but perhaps this is better handled by being explicit about voice in default mycroft.conf shipped by ovos-config

**Comment by mikejgray** [comment]
Are you sure you're on the right version? I fixed at least one of those

**Comment by mikejgray** [comment]
@JarbasAl

**Comment by mikejgray** [comment]
Closing, can't replicate, please reopen if it's still an issue
